// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using core;

namespace core.Migrations
{
    [DbContext(typeof(BloggingContext))]
    [Migration("20200617050547_WithoutIdentity")]
    partial class WithoutIdentity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("core.Adver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Advers");
                });

            modelBuilder.Entity("core.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BlogId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("core.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostId");

                    b.HasIndex("BlogId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("core.TcategoryGoods", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentID");

                    b.ToTable("TcategoryGoodss");
                });

            modelBuilder.Entity("core.TcategoryStore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentID");

                    b.ToTable("TcategoryStores");
                });

            modelBuilder.Entity("core.Tgoods", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abstract")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GoodsStatus")
                        .HasColumnType("int");

                    b.Property<int>("GoodsType")
                        .HasColumnType("int");

                    b.Property<bool>("IsConfirm")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFreeDeliveryExist")
                        .HasColumnType("bit");

                    b.Property<int>("TcategoryGoodsId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TstoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TcategoryGoodsId");

                    b.HasIndex("TstoreId");

                    b.ToTable("Tgoodses");
                });

            modelBuilder.Entity("core.TgoodsAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int?>("GoodsCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Required")
                        .HasColumnType("bit");

                    b.Property<int>("TattributeType")
                        .HasColumnType("int");

                    b.Property<int>("TgoodsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TgoodsId");

                    b.ToTable("TgoodsAttributes");
                });

            modelBuilder.Entity("core.TgoodsAttributeValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TgoodsAttributeId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TgoodsAttributeId");

                    b.ToTable("TgoodsAttributeValues");
                });

            modelBuilder.Entity("core.TgoodsImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TgoodsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TgoodsId");

                    b.ToTable("TgoodsImages");
                });

            modelBuilder.Entity("core.TgoodsPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TgoodsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TgoodsId");

                    b.ToTable("TgoodsPrices");
                });

            modelBuilder.Entity("core.Torder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TfactorId")
                        .HasColumnType("int");

                    b.Property<int>("TgoodsId")
                        .HasColumnType("int");

                    b.Property<int>("TorderStatus")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TgoodsId");

                    b.ToTable("Torders");
                });

            modelBuilder.Entity("core.TordergoodsAttributeValues", b =>
                {
                    b.Property<int>("TorderId")
                        .HasColumnType("int");

                    b.Property<int>("GoodsAttributeValueId")
                        .HasColumnType("int");

                    b.Property<int?>("TgoodsAttributeValueId")
                        .HasColumnType("int");

                    b.HasKey("TorderId", "GoodsAttributeValueId");

                    b.HasIndex("TgoodsAttributeValueId");

                    b.ToTable("TordergoodsAttributeValues");
                });

            modelBuilder.Entity("core.Tstore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsConfirm")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFreeDeliveryExist")
                        .HasColumnType("bit");

                    b.Property<int>("TcategoryStoreId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserOwner")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TcategoryStoreId");

                    b.ToTable("Tstores");
                });

            modelBuilder.Entity("core.Post", b =>
                {
                    b.HasOne("core.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("core.TcategoryGoods", b =>
                {
                    b.HasOne("core.TcategoryGoods", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentID");
                });

            modelBuilder.Entity("core.TcategoryStore", b =>
                {
                    b.HasOne("core.TcategoryStore", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentID");
                });

            modelBuilder.Entity("core.Tgoods", b =>
                {
                    b.HasOne("core.TcategoryGoods", "TcategoryGoods")
                        .WithMany("Tgoodses")
                        .HasForeignKey("TcategoryGoodsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("core.Tstore", "Tstore")
                        .WithMany("Tgoodses")
                        .HasForeignKey("TstoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("core.TgoodsAttribute", b =>
                {
                    b.HasOne("core.Tgoods", "Tgoods")
                        .WithMany("TgoodsAttributes")
                        .HasForeignKey("TgoodsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("core.TgoodsAttributeValue", b =>
                {
                    b.HasOne("core.TgoodsAttribute", "TgoodsAttribute")
                        .WithMany("TgoodsAttributeValues")
                        .HasForeignKey("TgoodsAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("core.TgoodsImage", b =>
                {
                    b.HasOne("core.Tgoods", "Tgoods")
                        .WithMany("TgoodsImages")
                        .HasForeignKey("TgoodsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("core.TgoodsPrice", b =>
                {
                    b.HasOne("core.Tgoods", "Tgoods")
                        .WithMany("TgoodsPrices")
                        .HasForeignKey("TgoodsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("core.Torder", b =>
                {
                    b.HasOne("core.Tgoods", "Tgoods")
                        .WithMany("Torders")
                        .HasForeignKey("TgoodsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("core.TordergoodsAttributeValues", b =>
                {
                    b.HasOne("core.TgoodsAttributeValue", "TgoodsAttributeValue")
                        .WithMany("TordergoodsAttributeValues")
                        .HasForeignKey("TgoodsAttributeValueId");

                    b.HasOne("core.Torder", "Torder")
                        .WithMany("TordergoodsAttributeValues")
                        .HasForeignKey("TorderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("core.Tstore", b =>
                {
                    b.HasOne("core.TcategoryStore", "TcategoryStore")
                        .WithMany("Tstores")
                        .HasForeignKey("TcategoryStoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
